version: '2'
services:
  web:
    build: ./flask_app
    ports:
      - "5000:5000"
    volumes:
      - ./flask_app:/app
    links:
      - mongodb
  mongodb:
    image: mongo:3.6
    container_name: mongodb
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
